//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkChronicle.Controls.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkChronicle.Controls.Resources.Localization.ControlAppResources", typeof(ControlAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit rest days. Try again!.
        /// </summary>
        public static string CantEditRestDays {
            get {
                return ResourceManager.GetString("CantEditRestDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Shift.
        /// </summary>
        public static string DayShift {
            get {
                return ResourceManager.GetString("DayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shift.
        /// </summary>
        public static string EditShift {
            get {
                return ResourceManager.GetString("EditShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is {0} long..
        /// </summary>
        public static string ItIsHoursLong {
            get {
                return ResourceManager.GetString("ItIsHoursLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Shift.
        /// </summary>
        public static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid shift type..
        /// </summary>
        public static string PleaseSelectValidShiftType {
            get {
                return ResourceManager.GetString("PleaseSelectValidShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest day.
        /// </summary>
        public static string RestDay {
            get {
                return ResourceManager.GetString("RestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Duration:.
        /// </summary>
        public static string ShiftHour {
            get {
                return ResourceManager.GetString("ShiftHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Type:.
        /// </summary>
        public static string ShiftType {
            get {
                return ResourceManager.GetString("ShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again!.
        /// </summary>
        public static string SomethingWentWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0}..
        /// </summary>
        public static string ThisIsA {
            get {
                return ResourceManager.GetString("ThisIsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is compensated!.
        /// </summary>
        public static string ThisShiftIsCompensated {
            get {
                return ResourceManager.GetString("ThisShiftIsCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is marked as a paid/unpaid leave..
        /// </summary>
        public static string ThisShiftIsMarkedAsVacation {
            get {
                return ResourceManager.GetString("ThisShiftIsMarkedAsVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is marked as sick leave..
        /// </summary>
        public static string ThisShiftIsMarkedSickLeave {
            get {
                return ResourceManager.GetString("ThisShiftIsMarkedSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift was supposed to last {0}, the hours are not worked, but are recorded as paid/unpaid leave hours and are subject to separate compensation according to the legislation..
        /// </summary>
        public static string ThisShiftWasSupposedLastHoursAreNotWorkedBecauseOfPaidLeave {
            get {
                return ResourceManager.GetString("ThisShiftWasSupposedLastHoursAreNotWorkedBecauseOfPaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift was supposed to last {0}, with the hours not worked, but recorded as sick leave and separate compensation due according to the legislation..
        /// </summary>
        public static string ThisShiftWasSupposedToLastHoursNotWorkedBecauseOfSickLeave {
            get {
                return ResourceManager.GetString("ThisShiftWasSupposedToLastHoursNotWorkedBecauseOfSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have compensated {0}.
        /// </summary>
        public static string YouHaveCompensatedHours {
            get {
                return ResourceManager.GetString("YouHaveCompensatedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You start the shift at {0}.
        /// </summary>
        public static string YouStartTheShiftAt {
            get {
                return ResourceManager.GetString("YouStartTheShiftAt", resourceCulture);
            }
        }
    }
}
