//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkChronicle.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkChronicle.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        public static string AboutTheApp {
            get {
                return ResourceManager.GetString("AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calculating the shifts. Try again!.
        /// </summary>
        public static string AnErrorOccurredWhileCalculatingTheShifts {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileCalculatingTheShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the year schedule. Try again!.
        /// </summary>
        public static string AnErrorOccurredWhileCreatingYearSchedule {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileCreatingYearSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A schedule for the month {0} already exists. Do you want to overwrite it?.
        /// </summary>
        public static string AScheduleForTheMonthAlreadyExistsToOverwrite {
            get {
                return ResourceManager.GetString("AScheduleForTheMonthAlreadyExistsToOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment work hours are available from the year 2021 up to 2026 (included)..
        /// </summary>
        public static string AtThisMomentWorkHoursAvailableFrom2021To2026 {
            get {
                return ResourceManager.GetString("AtThisMomentWorkHoursAvailableFrom2021To2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Schedule for {0} {1}.
        /// </summary>
        public static string CalendarWorkScheduleFor {
            get {
                return ResourceManager.GetString("CalendarWorkScheduleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensated.
        /// </summary>
        public static string Compensated {
            get {
                return ResourceManager.GetString("Compensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate.
        /// </summary>
        public static string CompensateSelectedShift {
            get {
                return ResourceManager.GetString("CompensateSelectedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a month schedule.
        /// </summary>
        public static string CreateANewMonthSchedule {
            get {
                return ResourceManager.GetString("CreateANewMonthSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a year schedule.
        /// </summary>
        public static string CreateAYearSchedule {
            get {
                return ResourceManager.GetString("CreateAYearSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a month schedule will override and delete a saved month schedule for the selected month. Do you want to continue?.
        /// </summary>
        public static string CreatingAMonthScheduleWillOverrideDeleteSavedMonthSchedule {
            get {
                return ResourceManager.GetString("CreatingAMonthScheduleWillOverrideDeleteSavedMonthSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a year schedule will override and delete saved month schedules for the {0} year. Do you want to continue?.
        /// </summary>
        public static string CreatingYearScheduleWillOverrideDeleteSavedMonthSchedulesForYear {
            get {
                return ResourceManager.GetString("CreatingYearScheduleWillOverrideDeleteSavedMonthSchedulesForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 24 Hour.
        /// </summary>
        public static string Day24Hour {
            get {
                return ResourceManager.GetString("Day24Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Day.
        /// </summary>
        public static string DayDay {
            get {
                return ResourceManager.GetString("DayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Night.
        /// </summary>
        public static string DayNight {
            get {
                return ResourceManager.GetString("DayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Night Night.
        /// </summary>
        public static string DayNightNight {
            get {
                return ResourceManager.GetString("DayNightNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day shift.
        /// </summary>
        public static string DayShift {
            get {
                return ResourceManager.GetString("DayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day shift second.
        /// </summary>
        public static string DayShiftSecond {
            get {
                return ResourceManager.GetString("DayShiftSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected schedule.
        /// </summary>
        public static string DeleteSelectedSchedule {
            get {
                return ResourceManager.GetString("DeleteSelectedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit and Save Schedule.
        /// </summary>
        public static string EditAndSaveSchedule {
            get {
                return ResourceManager.GetString("EditAndSaveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schedule.
        /// </summary>
        public static string EditSchedule {
            get {
                return ResourceManager.GetString("EditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditSelectedShift {
            get {
                return ResourceManager.GetString("EditSelectedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first shift:.
        /// </summary>
        public static string EnterFirstShift {
            get {
                return ResourceManager.GetString("EnterFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shift cycle pattern:.
        /// </summary>
        public static string EnterShiftCyclePattern {
            get {
                return ResourceManager.GetString("EnterShiftCyclePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Schedule.
        /// </summary>
        public static string GenerateSchedule {
            get {
                return ResourceManager.GetString("GenerateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Main.
        /// </summary>
        public static string GoBackToMain {
            get {
                return ResourceManager.GetString("GoBackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} hours of overtime, you can choose which shift to compensate..
        /// </summary>
        public static string HourMessageYouHaveHoursOfOvertime {
            get {
                return ResourceManager.GetString("HourMessageYouHaveHoursOfOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} hours under the total hours for the month. .
        /// </summary>
        public static string HourMessageYouHaveUnderTheTotalHoursForTheMonth {
            get {
                return ResourceManager.GetString("HourMessageYouHaveUnderTheTotalHoursForTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a 24HourDay schedule, {0} can&apos;t be select as first shift, please select {1}..
        /// </summary>
        public static string InA24HourdDayScheduleCantBeSelectedAsFirstShift {
            get {
                return ResourceManager.GetString("InA24HourdDayScheduleCantBeSelectedAsFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a Day-Day schedule, {0} can&apos;t be select as first shift, please select {1}..
        /// </summary>
        public static string InADayDayScheduleCantBeSelectFirstShift {
            get {
                return ResourceManager.GetString("InADayDayScheduleCantBeSelectFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a saved schedule.
        /// </summary>
        public static string LoadaSavedSchedule {
            get {
                return ResourceManager.GetString("LoadaSavedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load selected schedule.
        /// </summary>
        public static string LoadSelectedSchedule {
            get {
                return ResourceManager.GetString("LoadSelectedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid/Unpaid Leave.
        /// </summary>
        public static string MarkSelectedShiftPaidUnpaidLeave {
            get {
                return ResourceManager.GetString("MarkSelectedShiftPaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave.
        /// </summary>
        public static string MarkSelectedShiftSickLeave {
            get {
                return ResourceManager.GetString("MarkSelectedShiftSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night shift.
        /// </summary>
        public static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night shift Second.
        /// </summary>
        public static string NightShiftSecond {
            get {
                return ResourceManager.GetString("NightShiftSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No save schedule found!.
        /// </summary>
        public static string NoSaveScheduleFound {
            get {
                return ResourceManager.GetString("NoSaveScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid/Unpaid.
        /// </summary>
        public static string PaidUnpaidLeave {
            get {
                return ResourceManager.GetString("PaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a schedule..
        /// </summary>
        public static string PleaseSelectASchedule {
            get {
                return ResourceManager.GetString("PleaseSelectASchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a work schedule first!.
        /// </summary>
        public static string PleaseSelectAScheduleFirst {
            get {
                return ResourceManager.GetString("PleaseSelectAScheduleFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid work shift!.
        /// </summary>
        public static string PleaseSelectAValidWorkShift {
            get {
                return ResourceManager.GetString("PleaseSelectAValidWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press back again to exit!.
        /// </summary>
        public static string PressBackAgainToExit {
            get {
                return ResourceManager.GetString("PressBackAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev/Next Month .
        /// </summary>
        public static string PrevNextMonth {
            get {
                return ResourceManager.GetString("PrevNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string ReportAProblem {
            get {
                return ResourceManager.GetString("ReportAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Day .
        /// </summary>
        public static string RestDay {
            get {
                return ResourceManager.GetString("RestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Schedule.
        /// </summary>
        public static string SaveSchedule {
            get {
                return ResourceManager.GetString("SaveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule deleted successfully!.
        /// </summary>
        public static string ScheduleDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ScheduleDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Exists.
        /// </summary>
        public static string ScheduleExists {
            get {
                return ResourceManager.GetString("ScheduleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule not found, please try again!.
        /// </summary>
        public static string ScheduleNotFoundPleaseTryAgain {
            get {
                return ResourceManager.GetString("ScheduleNotFoundPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is compensated..
        /// </summary>
        public static string SelectedShiftIsCompensated {
            get {
                return ResourceManager.GetString("SelectedShiftIsCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is marked as in paid/unpaid leave and saved!.
        /// </summary>
        public static string SelectedShiftIsMarkedAsPaidUnpaidLeave {
            get {
                return ResourceManager.GetString("SelectedShiftIsMarkedAsPaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is marked as sick leave and saved!.
        /// </summary>
        public static string SelectedShiftIsMarkedAsSickLeaveDay {
            get {
                return ResourceManager.GetString("SelectedShiftIsMarkedAsSickLeaveDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is a working shift, again..
        /// </summary>
        public static string SelectedShiftIsWorkingShiftAgain {
            get {
                return ResourceManager.GetString("SelectedShiftIsWorkingShiftAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select First Shift.
        /// </summary>
        public static string SelectFirstShift {
            get {
                return ResourceManager.GetString("SelectFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shift Pattern.
        /// </summary>
        public static string SelectShiftPattern {
            get {
                return ResourceManager.GetString("SelectShiftPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting day of your work cycle:.
        /// </summary>
        public static string SelectStartingDayWorkCycle {
            get {
                return ResourceManager.GetString("SelectStartingDayWorkCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting time for the Day Shift:.
        /// </summary>
        public static string SelectStartingTimeForDayShift {
            get {
                return ResourceManager.GetString("SelectStartingTimeForDayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting time for the Night Shift:.
        /// </summary>
        public static string SelectStartingTimeForNigthShift {
            get {
                return ResourceManager.GetString("SelectStartingTimeForNigthShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Total Shift Hours:.
        /// </summary>
        public static string SelectTotalShiftHours {
            get {
                return ResourceManager.GetString("SelectTotalShiftHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave.
        /// </summary>
        public static string SickLeave {
            get {
                return ResourceManager.GetString("SickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, generate new schedule..
        /// </summary>
        public static string SomethingWentWrongGeneratedNewSchedule {
            get {
                return ResourceManager.GetString("SomethingWentWrongGeneratedNewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again!.
        /// </summary>
        public static string SomethingWentWrongPleaseTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of those hours you have {0} hours reported as sick leave..
        /// </summary>
        public static string TextMessageOutOfThoseHoursYouHaveHorusOnSickLeave {
            get {
                return ResourceManager.GetString("TextMessageOutOfThoseHoursYouHaveHorusOnSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of those hours you have {0} hours reported as paid/unpaid leave..
        /// </summary>
        public static string TextMessageOutToseHoursYouHaveHoursReportedPaidUnpaidLeave {
            get {
                return ResourceManager.GetString("TextMessageOutToseHoursYouHaveHoursReportedPaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a calendar for the {0} {1}!.
        /// </summary>
        public static string TextMessageThisIsACalendar {
            get {
                return ResourceManager.GetString("TextMessageThisIsACalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total hours for the month {0} are {1} hours , the working hours for that month are: {2} hours..
        /// </summary>
        public static string TextMessageTotalHoursAreForTheMonthAndWorkingHours {
            get {
                return ResourceManager.GetString("TextMessageTotalHoursAreForTheMonthAndWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app language has been changed to {0}. You need to restart the app again!.
        /// </summary>
        public static string TheAppLanguageHasBeenChanged {
            get {
                return ResourceManager.GetString("TheAppLanguageHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has been changed..
        /// </summary>
        public static string TheAppThemeHasBeenChanged {
            get {
                return ResourceManager.GetString("TheAppThemeHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total shift hours must be a positive number!.
        /// </summary>
        public static string TheTotalShiftHoursMustBepositiveNumber {
            get {
                return ResourceManager.GetString("TheTotalShiftHoursMustBepositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is marked as sick leave and cannot be marked as paid/unpaid leave!.
        /// </summary>
        public static string ThiShiftMarkedSickLeaveCannotMarkedPaidUnpaidLeave {
            get {
                return ResourceManager.GetString("ThiShiftMarkedSickLeaveCannotMarkedPaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a compensated shift and must first be converted to a working one in order to turned to sick leave..
        /// </summary>
        public static string ThisIsACompensatedSiftAndFirstMustBeConvertedToWork {
            get {
                return ResourceManager.GetString("ThisIsACompensatedSiftAndFirstMustBeConvertedToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a paid leave and it can&apos;t be compensated!.
        /// </summary>
        public static string ThisIsAPaidLeaveDayAndItCantBeCompensated {
            get {
                return ResourceManager.GetString("ThisIsAPaidLeaveDayAndItCantBeCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a rest day..
        /// </summary>
        public static string ThisIsARestDay {
            get {
                return ResourceManager.GetString("ThisIsARestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a rest day and it can&apos;t be compensated!.
        /// </summary>
        public static string ThisIsARestDayAndItCantBeCompensated {
            get {
                return ResourceManager.GetString("ThisIsARestDayAndItCantBeCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was a rest day and paid/unpaid Leave..
        /// </summary>
        public static string ThisIsARestDayAndPaidUnpaidLeave {
            get {
                return ResourceManager.GetString("ThisIsARestDayAndPaidUnpaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was a rest day and sick Leave..
        /// </summary>
        public static string ThisIsARestDayAndSickLeave {
            get {
                return ResourceManager.GetString("ThisIsARestDayAndSickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sick leave and it can&apos;t be compensated!.
        /// </summary>
        public static string ThisIsASickLeaveDayAndItCantBeCompensated {
            get {
                return ResourceManager.GetString("ThisIsASickLeaveDayAndItCantBeCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is not in the current month..
        /// </summary>
        public static string ThisShiftIsNotInTheCurrentMonth {
            get {
                return ResourceManager.GetString("ThisShiftIsNotInTheCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is marked as on paid/unpaid leave and must first be converted to a working one in order to turned to sick leave..
        /// </summary>
        public static string ThisShiftMarkedOnPaidLeaveMustFirstConvertedWorking {
            get {
                return ResourceManager.GetString("ThisShiftMarkedOnPaidLeaveMustFirstConvertedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is marked as on sick leave and cannot be marked as on paid leave!.
        /// </summary>
        public static string ThisShiftMarkedSickLeaveCannotBeMarkedAsPaidLeave {
            get {
                return ResourceManager.GetString("ThisShiftMarkedSickLeaveCannotBeMarkedAsPaidLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the select schedule. Do you want to continue?.
        /// </summary>
        public static string ThisWillDeleteTheScheduleDoContinue {
            get {
                return ResourceManager.GetString("ThisWillDeleteTheScheduleDoContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Chronicle.
        /// </summary>
        public static string WelcomeToTheWorkChronicle {
            get {
                return ResourceManager.GetString("WelcomeToTheWorkChronicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have loaded the {0} schedule for the {1}..
        /// </summary>
        public static string YouHaveLoadedTheScheduleForThe {
            get {
                return ResourceManager.GetString("YouHaveLoadedTheScheduleForThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no schedule for this month..
        /// </summary>
        public static string YouHaveNoScheduleForThisMonth {
            get {
                return ResourceManager.GetString("YouHaveNoScheduleForThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your schedule has been saved..
        /// </summary>
        public static string YourScheduleHasBeenSaved {
            get {
                return ResourceManager.GetString("YourScheduleHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been compensated. If you don&apos;t want to lose the schedule create it first!..
        /// </summary>
        public static string YourShiftHasBeenCompensatedSaveItFirst {
            get {
                return ResourceManager.GetString("YourShiftHasBeenCompensatedSaveItFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been edited and saved!.
        /// </summary>
        public static string YourShiftHasBeenEdit {
            get {
                return ResourceManager.GetString("YourShiftHasBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been edited. If you don&apos;t want to lose the schedule create it first!..
        /// </summary>
        public static string YourShiftHasBeenEditSaveItFirst {
            get {
                return ResourceManager.GetString("YourShiftHasBeenEditSaveItFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been marked on sick leave. If you don&apos;t want to lose the schedule create it first!.
        /// </summary>
        public static string YourShiftHasBeenMarkedAsSickLeaveSaveItFirst {
            get {
                return ResourceManager.GetString("YourShiftHasBeenMarkedAsSickLeaveSaveItFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been marked on paid/unpaid leave. If you don&apos;t want to lose the schedule save it first!.
        /// </summary>
        public static string YourShiftHasBeenMarkedPaidUnpaidLeaveSaveItFirst {
            get {
                return ResourceManager.GetString("YourShiftHasBeenMarkedPaidUnpaidLeaveSaveItFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work schedule for the month {0} {1} has been created and saved. You can check your month schedule in the Select saved schedules page..
        /// </summary>
        public static string YourWorkScheduelForTheMonthHasBeenCreatedAndSaved {
            get {
                return ResourceManager.GetString("YourWorkScheduelForTheMonthHasBeenCreatedAndSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work schedule for the year {0} has been created and saved. You can check your month schedules in the Select saved schedules page..
        /// </summary>
        public static string YourWorkScheduleForTheYearHasBeenCreatedAndSaved {
            get {
                return ResourceManager.GetString("YourWorkScheduleForTheYearHasBeenCreatedAndSaved", resourceCulture);
            }
        }
    }
}
